spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 #in query 갯수
      #show_sql : true #콘솔에 로그가 나옴
logging.level:
  org.hibernate.SQL: debug
